name: WisbeeRAG
options:
  bundleIdPrefix: com.wisbee
  deploymentTarget:
    iOS: 17.0
    macOS: 14.0
packages:
  LangChain:
    url: https://github.com/buhe/langchain-swift
    branch: main
  ObjectBox:
    url: https://github.com/objectbox/objectbox-swift
    from: 1.9.2
targets:
  WisbeeRAG:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources/AllInOne.swift
        buildPhase: sources
    dependencies:
      - package: LangChain
        product: LangChain
      - package: ObjectBox
        product: ObjectBox
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.wisbee.rag
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: 
        - UIInterfaceOrientationPortrait
        - UIInterfaceOrientationLandscapeLeft
        - UIInterfaceOrientationLandscapeRight
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
        - UIInterfaceOrientationPortrait
        - UIInterfaceOrientationPortraitUpsideDown
        - UIInterfaceOrientationLandscapeLeft
        - UIInterfaceOrientationLandscapeRight
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 5.9